// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-U60r_ZMVdAHqAUpZjf7JwF_oZ_TYKE8',
    appId: '1:1080661330819:web:08769d1f056e3546b6c4b6',
    messagingSenderId: '1080661330819',
    projectId: 'ramadhanapp-261f6',
    authDomain: 'ramadhanapp-261f6.firebaseapp.com',
    storageBucket: 'ramadhanapp-261f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtF8q9xkcksRpaFjH6L9aZx9hrRrxG3o',
    appId: '1:1080661330819:android:ab2e07599c918d12b6c4b6',
    messagingSenderId: '1080661330819',
    projectId: 'ramadhanapp-261f6',
    storageBucket: 'ramadhanapp-261f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTbEEeM-Z82j0njM4FOzu3guJJuAPVws',
    appId: '1:1080661330819:ios:3e53323f6caf78bdb6c4b6',
    messagingSenderId: '1080661330819',
    projectId: 'ramadhanapp-261f6',
    storageBucket: 'ramadhanapp-261f6.firebasestorage.app',
    iosBundleId: 'com.ramadhan.app.ramadhanFlutter',
  );
}
